#!/usr/bin/env python
"""Every number quoted in gold_figures_memo.tex, recomputed from the raw pulls.

The memo is written around four finished figures that were rendered elsewhere.
Nothing here redraws them; this file exists so that each quantitative claim in
the prose can be traced to a line of output rather than to a figure read by eye.

Run from the repo root:

    .venv/Scripts/python.exe claude/figures-memo/stats/memo_stats.py \
        > claude/figures-memo/stats/memo_stats.txt

Inputs are the raw pulls under gold_final/data/raw/, which are gitignored and
regenerated by gold_final/code/pull_us_customs.py and pull_databento.py. Three
numbers in the memo do not come from this file and are labelled where they
appear: the daily curve-fit diagnostics (gold_final/data/fig2.log), the
transfer-cost build-up (gold_final/letter/gold_letter.tex), and the Switzerland
share caveat (prep_wgc_demand.py).

Conventions, following CLAUDE.md: tonnes throughout, converted at the boundary
at 32,150.7 troy ounces to the tonne; monthly frequency; the LBMA PM monthly
mean as the price. Census reports value and not mass for HS 7108 and 7115, so
every tonnage here is DERIVED - customs value over the benchmark price - and is
labelled as derived wherever the memo uses it.
"""

import pandas as pd
import numpy as np

RAW = "gold_final/data/raw/"
OZ_PER_T = 32150.7
GOLD_HS4 = [7108, 7115]

# Phase windows, matching figure 1's three-point paths.
PHASES = [
    ("baseline", "2023-11-01", "2024-10-01"),
    ("surge",    "2024-11-01", "2025-03-01"),
    ("reversal", "2025-04-01", "2025-11-01"),
]

# The five destinations figure 2's lower panel reads off the trade data, and
# the generous US-supplied share applied to each one's demand.
FIVE = ["hong_kong", "india", "singapore", "switzerland", "united_kingdom"]
FIVE_CENSUS = {
    "SWITZERLAND": "switzerland", "UNITED KINGDOM": "united_kingdom",
    "HONG KONG": "hong_kong", "INDIA": "india", "SINGAPORE": "singapore",
}


def hr(title):
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


# ---------------------------------------------------------------- the inputs

gold = pd.read_csv(RAW + "us_gold_monthly.csv", parse_dates=["date"])
gold = gold[gold.hs4.isin(GOLD_HS4)]
g = gold.groupby(["date", "flow"]).value_usd.sum().unstack()
g = g[g.index >= "2015-01-01"]

lbma = pd.read_csv(RAW + "lbma_pm.csv", parse_dates=["date"])
px = lbma.set_index("date").lbma_pm_usd.resample("MS").mean()
g["px"] = px.reindex(g.index)
g["imp_t"] = g["imports"] / g.px / OZ_PER_T          # derived tonnage
g["exp_t"] = g["exports"] / g.px / OZ_PER_T          # derived tonnage
g["net_v"] = g["imports"] - g["exports"]

macro = pd.read_csv(RAW + "us_deflator_inputs_monthly.csv",
                    parse_dates=["date"]).set_index("date")

hr("COVERAGE")
print(f"gold months        : {g.index.min():%Y-%m} to {g.index.max():%Y-%m}  "
      f"({len(g)} months)")
print(f"LBMA PM daily obs  : {len(lbma)}")

# ======================================================== FIGURE 1: the panel

hr("FIGURE 1  gold came in, then went back out")

bop_imp = macro.bopgimp * 1e6                        # BOP goods imports, $
share = (g["imports"] / bop_imp.reindex(g.index)).dropna()
print(f"gold imports, 2015-2019: min ${g['imports']['2015':'2019'].min()/1e9:.2f}bn  "
      f"max ${g['imports']['2015':'2019'].max()/1e9:.2f}bn  "
      f"mean ${g['imports']['2015':'2019'].mean()/1e9:.2f}bn a month")
print(f"gold share of BOP goods imports, 2015-2019 mean : {share['2015':'2019'].mean()*100:.2f}%")
print("largest monthly shares:")
for d, v in share.sort_values(ascending=False).head(5).items():
    print(f"   {d:%Y-%m}  {v*100:5.1f}%   (${g['imports'][d]/1e9:.1f}bn)")

print("\nphase means, $bn a month:")
for name, a, b in PHASES:
    s = g.loc[a:b]
    print(f"   {name:9s} imports {s['imports'].mean()/1e9:6.2f}   "
          f"exports {s['exports'].mean()/1e9:6.2f}")

gross = (g["imports"].sum() + g["exports"].sum()) / 1e9
net = g["net_v"].sum() / 1e9
print(f"\nsince 2015: gross ${gross:.0f}bn, net ${net:+.0f}bn "
      f"({abs(net)/gross*100:.0f}% of gross, pointing outward)")

cum = g["net_v"].loc["2024-11-01":].cumsum() / 1e9
print(f"cumulative net from Nov 2024: peak ${cum.max():+.1f}bn ({cum.idxmax():%Y-%m}), "
      f"${cum.iloc[-1]:+.1f}bn by {cum.index[-1]:%Y-%m}")
crossing = cum[cum < 0].index.min()
print(f"crosses zero in {crossing:%Y-%m}")

# Partner panel. Census returns aggregates (OECD, EUROPE, 1XXX continents) on
# the same endpoint; real countries are the four-digit codes not starting zero.
p = pd.read_csv(RAW + "us_gold_partner_monthly.csv", parse_dates=["date"])
p = p[p.hs4.isin(GOLD_HS4) & (p.date >= "2015-01-01")]
p = p[p.cty_code.astype(str).str.match(r"^[1-9]\d{3}$")]

print("\nSwitzerland's share of identified gold trade, by phase:")
for name, a, b in PHASES:
    s = p[(p.date >= a) & (p.date <= b)]
    si = s[s.flow == "imports"].groupby("cty_name").value_usd.sum()
    se = s[s.flow == "exports"].groupby("cty_name").value_usd.sum()
    print(f"   {name:9s} {si['SWITZERLAND']/si.sum()*100:4.0f}% of imports   "
          f"{se['SWITZERLAND']/se.sum()*100:4.0f}% of exports")

ex_p = p[p.flow == "exports"].groupby("cty_name").value_usd.sum().sort_values(ascending=False)
im_p = p[p.flow == "imports"].groupby("cty_name").value_usd.sum().sort_values(ascending=False)
print(f"\nSwitzerland, whole window: {im_p['SWITZERLAND']/im_p.sum()*100:.0f}% of identified "
      f"imports, {ex_p['SWITZERLAND']/ex_p.sum()*100:.0f}% of identified exports")

# ======================================================= FIGURE 2: the demand

hr("FIGURE 2  the flows against what the metal is used for")

wgc = pd.read_csv(RAW + "wgc_demand_quarterly.csv", parse_dates=["date"])
# Switzerland's jewellery demand sits inside a WGC regional aggregate and is
# not published separately, so Switzerland contributes bar and coin only and
# the partner benchmark is marginally understated.
wgc["tot"] = wgc.jewellery_t.fillna(0) + wgc.barcoin_t.fillna(0)


def monthly(country):
    s = wgc[wgc.country == country].set_index("date").tot
    return (s.resample("MS").ffill() / 3.0).reindex(g.index)


us_d = monthly("united_states")
shares = pd.read_csv(RAW + "us_import_shares.csv").set_index("country").generous_share
bench = pd.DataFrame({c: monthly(c) * shares[c] for c in FIVE})
bench["tot"] = bench.sum(axis=1)

print("UPPER PANEL - imports against US demand (jewellery plus bar and coin)")
print(f"   US demand   : mean {us_d.mean():.1f} t a month, "
      f"max {us_d.max():.1f}, min {us_d.min():.1f}")
print(f"   US imports  : mean {g.imp_t.mean():.1f} t a month")
print(f"   imports exceed demand in {(g.imp_t > us_d).sum()} of {len(g)} months")
jan = "2025-01-01"
print(f"   Jan 2025    : {g.imp_t[jan]:.0f} t imported against {us_d[jan]:.1f} t of demand "
      f"-> {g.imp_t[jan]/us_d[jan]:.0f}x")
print(f"   Nov24-Mar25 : {g.imp_t['2024-11-01':'2025-03-01'].sum():.0f} t against "
      f"{us_d['2024-11-01':'2025-03-01'].sum():.0f} t -> "
      f"{g.imp_t['2024-11-01':'2025-03-01'].sum()/us_d['2024-11-01':'2025-03-01'].sum():.0f}x")
q_us = wgc[wgc.country == 'united_states'].set_index('date').tot
print(f"   quarterly US demand since 2015: mean {q_us['2015':].mean():.1f} t, "
      f"max {q_us['2015':].max():.1f} t; 2025Q1 {q_us['2025-01-01']:.1f} t against "
      f"{g.imp_t['2025-01-01':'2025-03-01'].sum():.0f} t imported "
      f"-> {g.imp_t['2025-01-01':'2025-03-01'].sum()/q_us['2025-01-01']:.0f}x")
print(f"   whole window: {g.imp_t.sum():.0f} t imported against {us_d.sum():.0f} t of demand")

print("\nLOWER PANEL - exports against reachable foreign demand")
five_tot = ex_p[list(FIVE_CENSUS)].sum()
print(f"   the five take {five_tot/ex_p.sum()*100:.1f}% of US gold exports to identified countries")
for name, slug in FIVE_CENSUS.items():
    print(f"      {name:16s} {ex_p[name]/five_tot*100:5.1f}% of the five's tonnage, "
          f"share applied {shares[slug]:.0%}")
print(f"   benchmark   : mean {bench.tot.mean():.1f} t a month, max {bench.tot.max():.1f}")
print(f"      India contributes {bench.india.mean():.1f} t of it "
      f"({bench.india.mean()/bench.tot.mean()*100:.0f}% of the benchmark)")
print(f"   US exports  : mean {g.exp_t.mean():.1f} t a month -> "
      f"{g.exp_t.mean()/bench.tot.mean():.1f}x the benchmark")
print(f"   exports exceed the benchmark in {(g.exp_t > bench.tot).sum()} of {len(g)} months")
pk = g.exp_t.idxmax()
print(f"   peak        : {g.exp_t.max():.0f} t in {pk:%Y-%m} against "
      f"{bench.tot[pk]:.1f} t -> {g.exp_t.max()/bench.tot[pk]:.0f}x")
print(f"   whole window: {g.exp_t.sum():.0f} t exported against {bench.tot.sum():.0f} t reachable")

# ======================================================== FIGURE 3: the spread

hr("FIGURE 3  the spread and the metal that followed it")
print("Curve-fit diagnostics are not recomputed here; they are printed by")
print("gold_final/code/fig2_spread_vs_hurdle.do into gold_final/data/fig2.log:")
print("   2,862 days in the fit, 2,851 re-timed to the London auction")
print("   re-timing cuts the premium's sd from 0.499% to 0.235%")
print("   851 days clear the band westward (29.7%), 1,287 eastward (45.0%)")
print("The hurdle, $0.75 an ounce each way, is built up in gold_final/letter:")
print("   $0.35 COMEX depository delivery-out + $0.20 air freight + $0.20 recasting")
print("The episode cost, $243m [$85m, $520m] over 1,632 tonne-legs carrying")
print("$174bn of metal - 0.14% of the value moved - is from the same source.")

print("\nLower panel, recomputed here (derived tonnage, both headings):")
east = (g.imp_t - g.exp_t) < 0
print(f"   {len(g)} months with flow, {east.sum()} of them net eastward")
ep = (g.imp_t - g.exp_t)["2024-12-01":"2025-03-01"].sum()
af = (g.imp_t - g.exp_t)["2025-04-01":"2025-08-01"].sum()
print(f"   Dec 2024 - Mar 2025 : {ep:+.0f} t net west")
print(f"   Apr 2025 - Aug 2025 : {af:+.0f} t net")
print(f"   largest single month: {(g.imp_t-g.exp_t).max():+.0f} t "
      f"({(g.imp_t-g.exp_t).idxmax():%Y-%m}), "
      f"{(g.imp_t-g.exp_t).min():+.0f} t ({(g.imp_t-g.exp_t).idxmin():%Y-%m})")

# ================================================= FIGURE 4: ITA against NIPA

hr("FIGURE 4  the same quarter's trade, measured twice")

# ITA is monthly $mn, seasonally adjusted, not annualised. Take the mean of the
# months present and multiply by 12, so a short quarter is not understated.
# NIPA is already quarterly $bn at an annual rate; carry its single value.
m = macro.join((g[["imports", "exports"]] / 1e9)
               .rename(columns={"imports": "gold_imp", "exports": "gold_exp"}))
m["ita_imp"] = m.bopgimp / 1000
m["ita_exp"] = m.bopgexp / 1000
q = m.resample("QS").agg({"ita_imp": "mean", "ita_exp": "mean",
                          "gold_imp": "mean", "gold_exp": "mean",
                          "a255rc1q027sbea": "first", "a253rc1q027sbea": "first"})
for c in ["ita_imp", "ita_exp", "gold_imp", "gold_exp"]:
    q[c] *= 12
q = q.rename(columns={"a255rc1q027sbea": "nipa_imp", "a253rc1q027sbea": "nipa_exp"})
q = q.dropna(subset=["ita_imp", "nipa_imp", "ita_exp", "nipa_exp"])
q = q[q.index >= "2015-01-01"]
q["adj_imp"] = q.ita_imp - q.gold_imp
q["adj_exp"] = q.ita_exp - q.gold_exp

print(f"{len(q)} quarters, {q.index.min():%Yq%m} to {q.index.max():%Yq%m}, $bn at annual rates")
for side, label in [("imp", "IMPORTS"), ("exp", "EXPORTS")]:
    gap = q["ita_" + side] - q["nipa_" + side]
    adj = q["adj_" + side] - q["nipa_" + side]
    print(f"\n{label}")
    print(f"   mean |ITA - NIPA| {gap.abs().mean():6.1f}   largest {gap.abs().max():6.1f} "
          f"in {gap.abs().idxmax().to_period('Q')}")
    print(f"   mean |adj - NIPA| {adj.abs().mean():6.1f}   largest {adj.abs().max():6.1f}")
    print(f"   sd of the gap     {gap.std():6.1f}  ->  {adj.std():6.1f}")
    print(f"   signed mean       {gap.mean():+6.1f}  ->  {adj.mean():+6.1f}   "
          f"(the adjusted line sits slightly below NIPA: removing all of 7108+7115")
    print(f"                              overshoots what NIPA nets out)")
    print(f"   corr(gap, gold on this side) = {gap.corr(q['gold_' + side]):.3f}")

q["bal_ita"] = q.ita_imp - q.ita_exp
q["bal_nipa"] = q.nipa_imp - q.nipa_exp
q["bal_adj"] = q.adj_imp - q.adj_exp
q["netgold"] = q.gold_imp - q.gold_exp
bgap = q.bal_ita - q.bal_nipa
agap = q.bal_adj - q.bal_nipa

print("\nTHE BALANCE (not plotted; the panels show the flows apart so that an")
print("import error and an export error of the same sign cannot cancel)")
print(f"   mean |ITA - NIPA| {bgap.abs().mean():.1f}  ->  adjusted {agap.abs().mean():.1f}")
print(f"   2025Q1 gap {bgap['2025-01-01']:.0f}  ->  {agap['2025-01-01']:.0f}   "
      f"(ITA deficit {q.bal_ita['2025-01-01']:.0f} against NIPA {q.bal_nipa['2025-01-01']:.0f})")
print(f"   2025Q1 gap as a share of the NIPA balance: "
      f"{bgap['2025-01-01']/q.bal_nipa['2025-01-01']*100:+.1f}%")
print(f"   2026Q1, four quarters later:              "
      f"{bgap['2026-01-01']/q.bal_nipa['2026-01-01']*100:+.1f}%")
print(f"   corr(gap, net gold) = {bgap.corr(q.netgold):.3f}")

d_ita, d_nipa, d_adj = q.bal_ita.diff(), q.bal_nipa.diff(), q.bal_adj.diff()
dis = (np.sign(d_ita) != np.sign(d_nipa)) & d_ita.notna()
dis_a = (np.sign(d_adj) != np.sign(d_nipa)) & d_adj.notna()
print(f"\n   {d_ita.notna().sum()} quarterly changes; the two measures disagree about "
      f"direction {dis.sum()} times")
print(f"   raw       : {[str(x.to_period('Q')) for x in q.index[dis]]}")
print(f"   adjusted  : {[str(x.to_period('Q')) for x in q.index[dis_a]]}")
print(f"   corr of quarterly changes {d_ita.corr(d_nipa):.3f}  ->  {d_adj.corr(d_nipa):.3f}")
print("\n   each disagreement, with the two candidate triggers:")
print("      quarter   dITA   dNIPA   d(net gold)   |dgold/dITA|   gold's level share")
for dt in q.index[dis]:
    dg = q.netgold.diff()[dt]
    print(f"      {str(dt.to_period('Q')):8s} {d_ita[dt]:+6.0f}  {d_nipa[dt]:+6.0f}   "
          f"{dg:+10.0f}   {abs(dg/d_ita[dt])*100:11.0f}%   "
          f"{q.gold_imp[dt]/q.ita_imp[dt]*100:14.1f}%")

# ================================================ the monthly release itself

hr("SECTION 5  the adjustment on the monthly headline")
bal = pd.read_csv(RAW + "us_trade_balance_monthly.csv",
                  parse_dates=["date"]).set_index("date").balance_usdmn / 1000
netg = (g["imports"] - g["exports"]) / 1e9
for dt in ["2025-01-01", "2025-03-01", "2025-10-01"]:
    print(f"   {pd.Timestamp(dt):%b %Y}: reported deficit ${-bal[dt]:.1f}bn, "
          f"${-(bal[dt] + netg[dt]):.1f}bn without the gold "
          f"(net gold ${netg[dt]:+.1f}bn)")
roll = netg.rolling(12).sum()
print(f"   rolling twelve-month deficit overstated by ${roll.max():.1f}bn at its peak, "
      f"{roll.idxmax():%b %Y}")
print("   (this balance is goods and services, the headline of the monthly release;")
print("    figure 4 is goods only, which is the basis NIPA table 1.1.5 reports)")
